version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    depends_on:
      - nginx
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - ${PWD}/storage/nginx-proxy/certs:/etc/nginx/certs:ro
      - ${PWD}/storage/nginx-proxy/etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ${PWD}/storage/nginx-proxy/usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  db:
    image: mariadb:10.3
    env_file:
      - env/db.env
    restart: always
    ports:
      - target: 3306
        published: 3306
    volumes:
     - ${PWD}/storage/db:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    depends_on:
      - flask
      - react
    volumes:
     - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    env_file:
      - env/nginx.env

  flask:
    depends_on:
      - db
    restart: always
    build:
      context: ../backend
      dockerfile: ${PWD}/Dockerfile-flask
    image: hoechenberger/webtaste-flask:latest
    ports:
      - target: 8000
        published: 8000
    env_file:
      - env/flask.env

  react:
    build:
      context: ../frontend/webtaste_frontend
      dockerfile: ${PWD}/Dockerfile-react
    image: hoechenberger/webtaste-react:latest
    depends_on:
      - flask
    restart: always
    ports:
      - target: 5000
        published: 5000
