FROM continuumio/miniconda3:latest

RUN conda update -y -n base conda
RUN conda install -y numpy scipy pandas openpyxl configobj future flask \
    flask-login sqlalchemy gunicorn passlib \
    mysqlclient configobj matplotlib pillow xlsxwriter
RUN pip install flask_restplus flask_sqlalchemy json-tricks
RUN pip install --no-deps psychopy
RUN conda clean --all -y

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "--forwarded-allow-ips=\"*\"", \
     "webtaste_backend.app:app"]
