FROM continuumio/miniconda3:latest

RUN conda update -y -n base -c defaults conda
RUN conda install -y -c conda-forge \
    flask flask-login flask-restplus flask-sqlalchemy \
    gunicorn passlib itsdangerous json_tricks mysqlclient \
    openpyxl configobj matplotlib-base pillow xlsxwriter future \
    "questplus >=2019.4"

# Install version of PsychoPy that supports QUEST+
RUN conda clean --all -y
# RUN pip install --no-deps "psychopy==3.2.4"
RUN pip install --no-deps https://github.com/hoechenberger/psychopy/archive/qp.zip

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "--forwarded-allow-ips=\"*\"", \
     "webtaste_backend.app:app"]
