FROM continuumio/miniconda3:latest

RUN conda update -y -n base conda
RUN conda install -y -c conda-forge \
    flask flask-login flask-restplus flask-sqlalchemy \
    gunicorn passlib itsdangerous json_tricks mysqlclient \
    openpyxl configobj matplotlib pillow xlsxwriter future \
    "questplus >=0.0.5"

# Install version of PsychoPy that supports QUEST+
RUN conda clean --all -y
RUN pip install --no-deps 'psychopy==3.2.3'

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "--forwarded-allow-ips=\"*\"", \
     "webtaste_backend.app:app"]
